Added support for the gp3 and io2 ebs volume types
chef/knife-ec2 pull request #677
Opened 2024-03-19 10:15 UTC by ashiqueps

…ypes

## Description

This PR will support the newly released `gp3` and `io2` volume types. 

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-03-20 11:15 UTC, nikhil2611 approved these changes

2024-03-28 14:02 UTC, ashiqueps commented on lib/chef/knife/ec2_server_create.rb
> +        if %w{io1 io2}.include?(config[:ebs_volume_type]) && config[:ebs_provisioned_iops].nil?
That's a great idea. I have updated it.

2024-03-28 16:51 UTC, tpowell-progress approved these changes

2024-03-28 16:52 UTC, tpowell-progress requested changes
Check the lint errors in the verify run

2024-04-02 20:19 UTC, tpowell-progress approved these changes

2024-04-02 20:20 UTC, merged